dopex-io/elvarg

apps/dapp/src/components/straddles/Deposits/DepositsTable.tsx
apps/dapp/src/components/straddles/Positions/PositionsTable.tsx
apps/dapp/src/components/straddles/TopBar.tsx
apps/dapp/src/pages/straddles/[poolName].tsx

momentarily when hopping between eth/rdpx/dpx straddles

fix(straddles): bug displaying positions (DOP-252)

---

apps/dapp/src/components/straddles/Stats/InfoBox.tsx
apps/dapp/src/components/straddles/Stats/index.tsx

fix(straddles): improve stats grid

---

apps/dapp/src/components/atlantics/InsuredPerps/ManageCard/ManagePosition/StrategyDetails.tsx
apps/dapp/src/components/atlantics/InsuredPerps/ManageCard/ManagePosition/index.tsx

feat(insured-perps): display options purchasable (DOP-319)

---

apps/dapp/src/components/atlantics/Charts/LiquidityBarGraph/index.tsx
apps/dapp/src/components/atlantics/Charts/index.tsx
apps/dapp/src/components/atlantics/Manage/ContractData/ExplorerLink.tsx
apps/dapp/src/components/atlantics/Manage/ContractData/index.tsx

fix(atlantic-pools): condense bar chart

---

apps/dapp/src/components/ssov/WritePositions/WritePositionData.tsx
apps/dapp/src/store/Vault/ssov/index.ts

https://linear.app/dopex/issue/DOP-327/fix-utilization-column-for-ssov-writers

fix: ssov write utilization (DOP-327)

---

apps/dapp/package.json
apps/dapp/src/components/common/InputWithTokenSelector/index.tsx
apps/dapp/src/components/ssov/DepositPanel/index.tsx
apps/dapp/src/components/ssov/PurchaseDialog/index.tsx
apps/dapp/src/constants/tokens.ts
apps/dapp/src/store/Vault/ssov/index.ts
apps/dapp/src/store/Wallet/index.ts
pnpm-lock.yaml

Requires merging the sdk for stMATIC address.

fix(ssov): deposit panel

---

apps/dapp/src/components/common/InputWithTokenSelector/index.tsx
apps/dapp/src/components/ssov/DepositPanel/index.tsx
apps/dapp/src/constants/tokens.ts

- unknown reward token symbol
- jumping between ssov pages did not update selected collateral symbol
I'm not sure what's the point of updateUserBalance() in apps/dapp/src/components/common/InputWithTokenSelector/index.tsx
The [updateUserBalance() callback](https://github.com/dopex-io/elvarg/compare/fix/ssov-bugs?expand=1#diff-68fd35333adc000fcc7344946351fd21873d6e1272ffab86d9f3db3a115c090bL59) does not get called within the handleDeposit() function when a transaction has been made, hence the user balance does not update. The fix uses [updateAssetBalances()](https://github.com/dopex-io/elvarg/compare/fix/ssov-bugs?expand=1#diff-91d891e907e5f4da6cc371a94986ef47e86d4b884df7bf8da45d7972a0baeca8L258) and [userAssetBalances](https://github.com/dopex-io/elvarg/compare/fix/ssov-bugs?expand=1#diff- …

fix: bugged balance update

---

apps/dapp/src/pages/scalps/[poolName].tsx
apps/dapp/src/pages/scalps/leaderboard/index.tsx
apps/dapp/src/store/Vault/scalps/index.ts

1. Zdte and scalps store has functions: getQuoteLpContract and getBaseLpContract. This confict was fixed by changing the names in scalps store 
2. Removed countdown from scalps leaderboards

fix: store getter names

---

apps/dapp/src/components/atlantics/InsuredPerps/Tables/Positions.tsx

Add missing useMEmo dependancies for useMemo state in AP pool deposit table
Run pnpm build to see if there are any warnings for missing useMemo dependencies in related components

fix: add useMemo dependancy

---

apps/dapp/src/components/zdte/Manage/PnlChart/index.tsx
apps/dapp/src/pages/zdte/[zdte].tsx

Fix react warnings on dependencies.
With @pair

fix: react warnings

---

apps/dapp/src/components/zdte/ZdteDexScreenerChart/index.tsx
apps/dapp/src/pages/zdte/[zdte].tsx
apps/dapp/src/store/Vault/zdte/index.ts

perf(zdte): load times test commit

---

apps/dapp/src/components/zdte/Manage/TradeCard/index.tsx

With @pair
| desktop |  <img width="367" alt="Screenshot 2023-05-11" src="https://github.com/dopex-io/elvarg/assets/85767768/2aac3db9-de0f-4a46-8f5e-92fc57fc1d80"> |  <img width="379" alt="Screenshot 2023-05-11 at 4 46 08 AM" src="https://github.com/dopex-io/elvarg/assets/85767768/816d6dca-bb2f-412c-b220-c504e0f77fcd">   |

fix(zdte): rounding of fee & premium

---

apps/dapp/src/pages/zdte/[zdte].tsx
apps/dapp/src/store/Vault/zdte/index.ts

With @pair
- subgraph volume differs for both assets

fix: subgraph vol

---

apps/dapp/src/components/zdte/Manage/TradeCard/TradeButton.tsx

fix(zdte): handle undefined zdte lp data

---

apps/dapp/src/wagmi-client/RabbyConnector.ts

fix: check rabby undefined

---

packages/sdk/src/addresses/index.ts

Adding CVX Weekly PUTs SSOV V3

feat: add cvx ssov

---

apps/dapp/src/components/ssov/Description/index.tsx
apps/dapp/src/components/ssov/SsovCard/index.tsx
apps/dapp/src/graphql/ssovs/getSsovPurchasesFromTimestamp.graphql
apps/dapp/src/pages/ssov/index.tsx
apps/dapp/src/store/Vault/ssov/index.ts

feat: ssov oi

---

apps/dapp/src/pages/ssov/index.tsx

feat: total oi vol

---

apps/dapp/src/components/ssov/DepositPanel/index.tsx

FIxing the way user token balance is updated as the previous implementation would only updated once and that is when the page loads. This was due to use of unrelated dependencies in a certain useEffect and never updating to new balance after a transaction has been sent.
Wrote a useCallback that updates token balance, it is called in a useEffect when the component initially loads, later it is called after a deposit transaction is made
Deposit in any ssov, click max button to see if old balance is in the input or the new balance

fix: update of user token balance

---

apps/dapp/src/store/Vault/olp/index.ts

Fix typo `underlyingLiquidityUsed` instead of `underlyingLiquidity` for utilization
With @pair

fix: underlyingUsedInUsd typo

---

apps/dapp/src/components/atlantics/Charts/LiquidityBarGraph/index.tsx
apps/dapp/src/components/atlantics/InsuredPerps/ManageCard/ManagePosition/index.tsx
apps/dapp/src/components/atlantics/InsuredPerps/ManageCard/Swap/index.tsx
apps/dapp/src/components/atlantics/InsuredPerps/Title/index.tsx
apps/dapp/src/components/atlantics/Manage/ContractData/index.tsx
apps/dapp/src/components/atlantics/Manage/ManageCard/index.tsx
apps/dapp/src/components/atlantics/Manage/ManageTitle.tsx
apps/dapp/src/components/atlantics/TokenSelector/index.tsx
apps/dapp/src/components/common/TokenSelector/index.tsx
apps/dapp/src/components/common/ZapIn/index.tsx
apps/dapp/src/pages/atlantics/manage/insured-perps/[ticker].tsx

Refactor usdc to usdc.e in atlantics page

refactor: atlantics usdc.e

---

apps/dapp/src/components/portfolio/Balances/index.tsx

Refactor usdc to usdc.e in portfolio page

refactor: portfolio usdc.e

---

apps/dapp/src/components/straddles/DepositCard/index.tsx
apps/dapp/src/components/straddles/Deposits/DepositsTable.tsx
apps/dapp/src/components/straddles/PurchaseCard/index.tsx

Refactor usdc to usdc.e in straddles page

refactor: straddles usdc.e

---

apps/dapp/src/store/Vault/zdte/index.ts

fix: compare using gt

---

apps/dapp/src/components/atlantics/InsuredPerps/Tables/Positions.tsx

Description:
Issue arising from mixed and improper usage of formatting functions.
Before:
After:

fix: refactor formatting fns

---

apps/dapp/src/components/scalps/TradeCard/index.tsx

Change limit price suggestion
[closes issue-427](https://linear.app/dopex/issue/DOP-427/update-limit-price-labels)
Nothing to comment
Not available
Open demo and try a limit order

fix: change price suggestion (DOP-427)

---

apps/dapp/src/components/ssov/WritePositions/WritePositionData.tsx
apps/dapp/src/components/ssov/WritePositions/index.tsx
apps/dapp/src/store/Vault/ssov/index.ts

Added option to stake a write position manually into ssov staking rewards

feat: option to stake

---

apps/dapp/src/components/olp/OlpHome/index.tsx

Sort OLP TVL
[closes issue-DOP-423](https://linear.app/dopex/issue/DOP-423/sort-olp-vaults-by-tvl)

feat: sort olp by tvl

---

apps/dapp/.graphclientrc.yml
apps/dapp/src/components/common/Share/ShareImage.tsx
apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
apps/dapp/src/components/straddles/Positions/OpenPositions/OpenPositionsTable.tsx
apps/dapp/src/components/straddles/Positions/index.tsx
apps/dapp/src/graphql/straddles/queries/getStraddlesUserSettledData.graphql
apps/dapp/src/graphql/straddles/queries/getStraddlesUserSettledDataPolygon.graphql
apps/dapp/src/utils/general/getExplorerTxURL.ts
apps/dapp/src/utils/general/index.ts

Display expired positions for straddles
[closes issue-DOP-342](https://linear.app/dopex/issue/DOP-342/show-older-settled-purchase-positions-for-straddles)

DOP-342/feat/straddles settled positions

---

apps/dapp/src/components/ssov/WritePositions/index.tsx

Makes users claim rewards before claiming

feat: claim before withdraw

---

apps/dapp/src/components/scalps/Positions/PositionsTable.tsx
apps/dapp/src/store/Vault/scalps/index.ts

1. Remove fees and premium from pnl when position is open
2. Remove time to expiry total minutes
Not available
Open demo link

fix: scalp positions table

---

apps/dapp/src/pages/ssov/index.tsx

fix: gql payload key

---

apps/dapp/src/components/ssov/WritePositions/WritePositionData.tsx

Hide stake button after the epoch is expired.

feat: hide stake after expiry

---

apps/dapp/src/components/scalps/DepositCard/index.tsx
apps/dapp/src/components/scalps/LimitOrderPopover/index.tsx
apps/dapp/src/components/scalps/Positions/PositionsTable.tsx
apps/dapp/src/components/scalps/Stats/index.tsx
apps/dapp/src/components/scalps/TopBar/index.tsx
apps/dapp/src/components/scalps/TradeCard/index.tsx
apps/dapp/src/components/scalps/WithdrawCard/index.tsx

Ensure quoteDecimals and baseDecimals exist before to use them
Change ! to ? in line of code where we use those variables
Not available
Open scalp page

fix: wait optionScalpData loads before to try to load decimals

---

apps/dapp/src/components/olp/ProvideLp/index.tsx

Make Provide LP dialog load if `olpData` is undefined.
n/a
go to olp/DPX-MONTHLY to see the dialog loading

fix: load provide lp dialog

---

apps/dapp/src/components/scalps/DepositCard/index.tsx
apps/dapp/src/components/scalps/WithdrawCard/index.tsx

Fix usdc.e symbol: https://linear.app/dopex/issue/DOP-441/scalp-reintroduced-change-usdc-to-usdce-for-lpdeposit-in-eth-and-arb

fix: usdc.e symbol

---

apps/dapp/src/components/straddles/PurchaseCard/index.tsx
apps/dapp/src/store/Vault/straddles/index.ts

Fix error when purchasing straddles on MATIC.
Closes https://linear.app/dopex/issue/DOP-447/cant-purchase-long-straddle-for-matic-on-polygon-chain
Purchase straddles on MATIC

Dop 447/cant purchase long straddle

---

apps/dapp/src/pages/_app.tsx
apps/dapp/src/store/Wallet/index.ts

Hashmail widget integration
Add script tag and target window hook
N/A
N/A

feat: add hashmail widget

---

apps/dapp/src/components/ssov-beta/AsidePanel/index.tsx

Maintain design integrity for user balance under the input panel in the new ssov page.
[closes issue-462](https://linear.app/dopex/issue/DOP-462/show-token-balance-on-the-ui)
Usage of bottomElement prop in the dopex-io/ui Input component 
| desktop |    <img width="513" alt="Screenshot 2023-08-15 at 5 08 10 PM" src="https://github.com/dopex-io/elvarg/assets/85767768/e4da5a0a-ecdb-4ddf-a1ca-e6c7d4f87514">    |   <img width="393" alt="Screenshot 2023-08-15 at 5 08 24 PM" src="https://github.com/dopex-io/elvarg/assets/85767768/31b9aabd-3bc1-43ad-807b-3fedd0183224">   |
Note the "Balance" and "Total Qty" rows in the panel. When user is buying, he views the total quantity below the input panel, and his …

fix(ssov-new): input panel bottom element (DOP-462)

---

apps/dapp/src/components/ssov-beta/Tables/Positions/WritePositions.tsx
apps/dapp/src/hooks/ssov/useSsovPositions.ts

Incorrect calculation of premium share in the write positions table. 
```ts
// Typo ?
const activeCollateralShare =
(checkpointData.totalCollateral * checkpointData.activeCollateral) /
checkpointData.totalCollateral;
// Fix
const activeCollateralShare =
(userCollateral * checkpointData.activeCollateral) /
checkpointData.totalCollateral;
```
Compare premiums between the current ssov ui and the ssov beta.

fix(ssov-beta): positions table premium accrued

---

apps/dapp/src/components/common/TableLayout/index.tsx

Implement table pagination as per Figma design.
Usage of react-table's pagination helpers for our implementation. 
| desktop |    <img width="959" alt="Screenshot 2023-08-29" src="https://github.com/dopex-io/elvarg/assets/85767768/59e78e8f-dc8d-4cd3-b34c-0ce377a6f1c1">    |   <img width="960" alt="Screenshot 2023-08-29" src="https://github.com/dopex-io/elvarg/assets/85767768/eb735c5b-e642-4947-a60d-c8d607dbde00">    |
This section is intentionally left blank.

feat: table pagination

---

apps/dapp/src/components/zdte/Positions/ClosedPositions/ClosedPositionsRow.tsx

With @pair
| desktop |        |  
|
go to share button on zdte.

fix: do not pad cg price

---

apps/dapp/src/components/straddles/Dialogs/Withdraw.tsx

Atlantic Straddles (Possibly only happening on MATIC Straddles)
Fix an issue with typescript ! symbol usage which broke the withdraw button on matic straddles
Remove ! symbol
Try to withdraw a MATIC Straddle deposit position

fix: matic straddles withdraw button

---

apps/dapp/src/components/olp/AllLpPositions/index.tsx
apps/dapp/src/components/olp/OlpHome/FeaturedOlp.tsx
apps/dapp/src/components/olp/OlpHome/OlpTableRow.tsx
apps/dapp/src/components/olp/OlpHome/index.tsx
apps/dapp/src/components/olp/ProvideLp/index.tsx
apps/dapp/src/components/olp/UserLpPositions/index.tsx

OLP Page crash
undefined checks

fix: olp crashes

---

apps/dapp/src/components/olp/AllLpPositions/AllPositionsTable.tsx
apps/dapp/src/components/olp/AllLpPositions/index.tsx
apps/dapp/src/components/olp/FillPosition/FillPositionDialog.tsx
apps/dapp/src/components/olp/FillPosition/index.tsx

Fix OLP fill dialog
[DOP-483](https://linear.app/dopex/issue/DOP-483/olp-dollararb-goes-blank-as-we-move-our-mouse-over-fill-lp-pop-up)
Change dialog implementation to dopex ui

fix: olp fill dialog (DOP-483)

---

apps/dapp/src/utils/math/blackScholes/greeks.ts
apps/dapp/src/utils/math/blackScholes/index.ts

chore: fix typo

---

apps/dapp/src/components/clamm/AsidePanel/components/InfoPanel.tsx
apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/BuyPositions.tsx
apps/dapp/src/components/clamm/StrikesChain/components/StrikesTable.tsx

1. Added utilization for strikes
2. Added breakeven for options positions
3. Fixed an issue when if a purchase or deposit fails, the select strikes would reset

feat (clamm): feedback changes (1)

---

apps/dapp/src/components/rdpx-v2/AsidePanel/alerts.ts
apps/dapp/src/components/rdpx-v2/Body/BondsBody/UserDataGrid.tsx
apps/dapp/src/components/rdpx-v2/Dialogs/RedeemReceiptTokens.tsx
apps/dapp/src/components/rdpx-v2/Tables/ColumnDefs/BondsColumn.tsx
apps/dapp/src/components/rdpx-v2/Tables/UserBonds.tsx
apps/dapp/src/constants/rdpx/initialStates.ts
apps/dapp/src/hooks/rdpx/usePerpPoolData.ts
apps/dapp/src/hooks/rdpx/useSubgraphQueries.ts

- vest and stake
- display user lp that is also sent to the staking rewards contract
- update delegate bonding alert info in aside panel

fix: several rdpx ui fixes

---

apps/dapp/codegen.ts
apps/dapp/src/components/rdpx-v2/Body/StrategyVault/index.tsx
apps/dapp/src/components/rdpx-v2/Tables/ColumnDefs/DepositHistoryColumn.tsx
apps/dapp/src/components/rdpx-v2/Tables/DepositHistory.tsx
apps/dapp/src/graphql/rdpx-v2/index.ts
apps/dapp/src/hooks/rdpx/useSubgraphQueries.ts

Add deposit history section in Perpetual Put Vault.

feat(rdpx-v2): ppv user deposit history

---

apps/dapp/src/components/rdpx-v2/Dialogs/RedeemReceiptTokens.tsx
apps/dapp/src/components/rdpx-v2/TitleBar/index.tsx

Account for rdpx in the LP contract's TVL. Also updates rteth redeem fee from 4% to 2%.

fix: perp put vault tvl

---

apps/dapp/src/components/rdpx-v2/Dialogs/ManageCommunalFarm.tsx
packages/ui/src/Dialog.tsx

fix: multiplier

---

apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/LPPositions.tsx
apps/dapp/src/utils/clamm/varrock/types.ts

feat(clamm): show timestamp of initial deposit (DOP-515)

---

apps/dapp/src/hooks/rdpx/useRewardAPR.ts

fix: update rdpx-v2 aprs (dop-518)

---

apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx
apps/dapp/src/components/clamm/PositionsTable/components/Positions/LPPositions/index.tsx

fix: positions summary responsiveness in mobile (DOP-549)

---

apps/dapp/src/components/clamm/AsidePanel/components/InfoPanel.tsx
apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx
apps/dapp/src/components/clamm/PositionsTable/components/Positions/LPPositions/index.tsx
apps/dapp/src/hooks/useUserBalance.ts

error message if the user does not have eth balance for the transaction 
try to purchase, deposit, approve with insufficient eth in your account for the transaction.

feat: check for eth balance for transaction

---

apps/dapp/src/components/clamm/AsidePanel/index.tsx

feat: upgrade notice

---

apps/dapp/src/pages/index.tsx

APY in landing page appears as NaN

fix: clamm apy

---

apps/dapp/src/components/rdpx-v2/AsidePanel/StakePanel/index.tsx
apps/dapp/src/components/rdpx-v2/AsidePanel/StrategyVaultPanel/index.tsx
apps/dapp/src/components/rdpx-v2/Body/Farm/Card/index.tsx
apps/dapp/src/components/rdpx-v2/Body/Farm/index.tsx
apps/dapp/src/components/rdpx-v2/Body/StrategyVault/UserDepositGrid/index.tsx
apps/dapp/src/components/rdpx-v2/Dialogs/LpAndBondStepper.tsx
apps/dapp/src/components/rdpx-v2/Dialogs/ManageCommunalFarm.tsx
apps/dapp/src/components/rdpx-v2/Dialogs/ManageFarm.tsx
apps/dapp/src/components/rdpx-v2/Dialogs/MigrateAndBond.tsx
apps/dapp/src/components/rdpx-v2/Tables/hooks/useRedeemBondsSteps.ts
apps/dapp/src/components/rdpx-v2/Tables/hooks/useRedeemDelegateBondsSteps.ts
apps/dapp/src/components/rdpx-v2/TitleBar/Banner.tsx
apps/dapp/src/pages/rdpx-v2/[[...index]].tsx

Prepare for rdpx-v2 sunset. See linear issue for more details.

refactor(rdpx-v2): prepare sunset (eng-587)

---

apps/dapp/src/abis/clamm/OptionPricingLinearV2.ts
apps/dapp/src/components/clamm/AsidePanel/components/CostSummary/components/ImpliedVolatility.tsx
apps/dapp/src/components/clamm/AsidePanel/components/CostSummary/index.tsx
apps/dapp/src/components/clamm/AsidePanel/components/SelectedStrikeItem/index.tsx

feat: display iv in aside panel (ENG-603)

---

apps/dapp/src/components/clamm/StrikesChain/components/StrikesTable.tsx

feat: dollar values in strikes chain (ENG-602)

---

apps/dapp/src/components/clamm/PositionsTable/components/Positions/columnHelpers/tradeHistory.tsx
apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/HistoryPositions.tsx
apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/PositionsTypeSelector.tsx
apps/dapp/src/components/clamm/PositionsTable/index.tsx

feat: trade history (ENG-600)

---

apps/dapp/src/components/rdpx-v2/Dialogs/ManageCommunalFarm.tsx

Revert the removal of rDPX Communal Farm Staking panel

fix: revert rdpx staking panel removal
