dopex-io/elvarg

- apps/dapp/src/components/olp/OlpHome/index.tsx
- apps/dapp/src/components/olp/Stats/index.tsx
- apps/dapp/src/store/Vault/olp/index.ts
Reduces page sizes by around 10 to 20 kb
Before:
After:
> refactor: lodash imports

- apps/dapp/src/style/index.css
Notice the different spacing above and below text getting fixed: 
Before
After
> Fixes line height for the custom font

- apps/dapp/src/components/scalps/Positions/PositionsTable.tsx
Implementing revised pnl % formula
[closes issue-365](https://linear.app/dopex/issue/DOP-365/option-scalps-pnl-percent-is-broken)
With @0xYYC we have decided to change the formula from
pnl / margin
to
pnl / (margin + fees + premium)
I've also changed the decimals used from 1 to 2
Not required
Open /scalps/ETH and check your closed positions PNLs
> fix: scalps pnl % (DOP-365)

- apps/dapp/src/components/scalps/Positions/PositionsTable.tsx
Update the handleShare() function of PositionsTable.tsx so the % pnl of the shareable card is the same of the one displayed in the table
[closes issue-373](https://linear.app/dopex/issue/DOP-373/option-scalps-share-card-percent-pnl-doesnt-match-with-table-pnl)
I copied the code used for the table.
What happens now is that fees and premium are added to margin.
None
Go to an option scalps vault and check your closed positions
> fix: pnl % share card

- apps/dapp/src/components/atlantics/InsuredPerps/ManageCard/Swap/index.tsx
- apps/dapp/src/components/atlantics/Manage/ContractData/ExplorerLink.tsx
[closes issue-DOP-368](https://linear.app/dopex/issue/DOP-368/insured-prep-swap-ui-when-swaping-usdc-to-weth)
With @pair
Trade -> Insured Perps -> Swap on right-hand side panel -> click the reverse button for token pair
> fix(atlantics): arbitrum icon

- apps/dapp/src/components/scalps/DepositCard/index.tsx
- apps/dapp/src/components/scalps/WithdrawCard/index.tsx
Some users reported they have issues when trying to max withdraw or deposit.
The issue is that using String() we round up the number if the last digit we support it's above 5.
I propose this solution which uses Math.floor() to round down.
[closes issue-374](https://linear.app/dopex/issue/DOP-374/fix-round-issue-when-max-depositing-or-withdrawing-from-scalps)
Using Math.floor() we can be sure we round down the number
None
Open demo deployment link and try to max deposit and withdraw
> fix: scalps deposits/withdrawing max amount round issues (DOP-374)

- apps/dapp/src/store/Vault/scalps/index.ts
The function updateScalpData() uses optionScalp which is null when the page loads.
We should check if that variable exists before to proceed.
It is a simple line which checks if optionScalpContract exists or skip the execution of the function
[closes issue-375](https://linear.app/dopex/issue/DOP-375/option-scalp-crashes-at-first-load)
if (!optionScalpContract) return;
Not available
Open the demo link https://dapp-git-fix-option-scalps-null-option-scalp-contract-dopex-io.vercel.app/scalps/ETH and see if the stats table appears correctly
> fix: option scalp invalid first load [DOP-375]

- apps/dapp/src/components/straddles/PurchaseCard/index.tsx
It's not possible to buy ETH with USDC using GMX right now.
With this PR I update the paths of DPX and RDPX straddles purchase so they use Uniswap v3 instead of GMX.
[closes issue-378](https://linear.app/dopex/issue/DOP-378/gmx-error-when-purchasing-rdpx-straddles)
Change path id from 5 to 6
Not available
Open the demo link and try to purchase DPX or rDPX straddles
> fix: use Uni V3 instead of GMX for straddles rdpx and dpx routes (DOP-378)

- apps/dapp/src/components/ssov/WritePositions/WritePositionData.tsx
[closes issue-DOP-377](https://linear.app/dopex/issue/DOP-377/fix-hide-0-rewards-from-ssov-writepositions)
The function returns the code only if rewards is greater than 0, otherwise it's null
Open the demo and check DPX ssov.  You must have a write position.
> fix: hide 0 rewards from ssov writepositions (DOP-377)

- apps/dapp/src/components/ssov/WritePositions/WritePositionData.tsx
Rewards should be visible if symbol == collateralSymbol even if they are 0
[closes issue-379](https://linear.app/dopex/issue/DOP-379/ssov-show-rewards-if-in-collateralsymbol)
Trivial check (if rewardTokens[index]?.symbol === collateralSymbol)
Not available
Open demo link and check WritePositions table of SSOV
> fix: ssov show rewards even if 0 if is collateralSymbol (DOP-379)

- apps/dapp/src/components/common/ConnectDialog/index.tsx
- apps/dapp/src/components/ssov/WritePositions/WritePositionData.tsx
[closes issue-380](https://linear.app/dopex/issue/DOP-380/wallet-dialog-use-injected-as-default-option)
Try to use last connector (injected) if the user chosen one doesn't work
Not available
Open the demo link and try to connect while metamask and rabby are installed
> fix: wallet dialog injected default option (DOP-380)

- apps/dapp/src/components/zdte/Manage/TradeCard/TradeButton.tsx
- apps/dapp/src/components/zdte/Manage/TradeCard/index.tsx
> fix(zdte): trade panel insufficient balance bug

- apps/dapp/src/components/ssov/PurchaseDialog/index.tsx
Fix margin top of strikes dropdown
[closes issue-345](https://linear.app/dopex/issue/DOP-345/strike-prices-dropdown-is-not-properly-aligned)
Remove mt-12
Not available
Open a SSOV from the demo link and try to purchase an option
> fix: strikes dropdown margin top (DOP-345)

- apps/dapp/src/components/ssov/DepositPanel/index.tsx
Fix ssov deposit card padding
[closes issue-346](https://linear.app/dopex/issue/DOP-346/no-padding-below-list-box)
Changes to tailwind classes
Not available
Open demo link and click on a SSOV
> fix: ssov padding (DOP-346)

- apps/dapp/src/components/ssov/Stats/SsovStat.tsx
- apps/dapp/src/pages/ssov/index.tsx
Restyled stats show on ssov index page to fit the design and adapt to screen size
With @pair
- remove bg box
- implemented the same way stats are displayed on ssov manage page
desktop:
Mobile: 
- Click "Show deployment" button on the latest commit
> feat(ssov): stats revamp

- apps/dapp/src/components/scalps/Orders/OrdersTable.tsx
- apps/dapp/src/components/scalps/Positions/PositionsTable.tsx
- apps/dapp/src/store/Vault/scalps/index.ts
This PR adds a column to the scalp orders table 'Target price', or the price that must be reach for your order to be filled.
The 'Estimated entry' will instead tells user what will be his entry after the order has been filled.
Use further range tick to compute the corresponding price.
Not available
Open demo link
> feat: show target price in scalp orders table

- apps/dapp/src/components/scalps/LimitOrderPopover/index.tsx
To save space we change the text of the button to "Limit"
Simple text replace and width adjustment
Not available
Open demo link
> fix: scalp positions table limit close button text

- apps/dapp/src/components/scalps/TradeCard/index.tsx
Show USDC.e instead of USDC
Show available balance
Show fees in green if it's a limit order
Nothing to report
Not available
See the demo
> fix: scalps trade card

- apps/dapp/src/components/ssov/Description/index.tsx
- apps/dapp/src/components/ssov/SsovCard/index.tsx
- apps/dapp/src/pages/scalps/leaderboard/index.tsx
% symbols were not added to ssov APYs
Before:
After:
> fix: Add percentage symbols

- apps/dapp/src/components/ssov/SsovCard/index.tsx
fix hitting back on a ssov page breaking dapp
pass href to the manage button
N/A
Go to ssov page on the preview link, click on a ssov and hit back, it should load back the ssov home page normally
> fix: hitting back on a ssov page breaks dapp (DOP-428)

- apps/dapp/src/components/ssov/Manage/index.tsx
- apps/dapp/src/store/Vault/ssov/index.ts
ssovSigner slice which holds instances of contracts with signer depends on the epoch of the SSOV. specifically the staking contract which has to return the legacy staking contract depending on the SSOV and epoch. Hence, I added a check to see if ssovData is available then update/load ssovSigner.
> fix: update ssov signer if ssov data has loaded (DOP-433)

- apps/dapp/src/store/Vault/ssov/index.ts
Problem: 
SsovViewer reverts when writePositionValue is called.
Solution:
Since writePositionValue() usage has been deprecated, and the only values from that we use are rewards and accruedPremiums for a writePosition, I've written code to calculate accrued premiums and disregarded rewards as we are now using staking rewards.
> feat: calc premiums

- apps/dapp/src/store/Farming/index.ts
Using anything above 1e14 of JS number data type with ethers big number will throw overflow error
> fix: ethers bn overflow

- apps/dapp/src/components/ssov/Description/index.tsx
> fix: extra percentage symbol

- apps/dapp/src/components/scalps/TradeCard/index.tsx
Disable open position button if position size is too large
Compare position size in quote with scalp contract maximum position size in quote
Not available
Open scalps page, try to open a huge position
> fix: show error if pos size is too large

- apps/dapp/src/components/olp/OlpHome/index.tsx
Sort OLP by TVL in desc order.
n/a
n/a
Go to /olp page and check if pools sorted by TVL in desc order
> Fix olp sort by tvl desc

- apps/dapp/src/components/ssov/PurchaseDialog/index.tsx
- apps/dapp/src/components/ssov/Stats/index.tsx
Issue:
When available collateral is calculated on the purchase dialog of an ssov, the collateral exchange rate is not considered.
Solution:
Consider collateral exchange rate when calculating available collateral
Before: (Note that purchase dialog is not considering collateral exchange rate so the available collateral shows lesser)
Purchase dialog:
Stats table:
After:
> fix: consider collateral exchange rate for purchase (DOP-439)

- apps/dapp/src/components/atlantics/Manage/ManageCard/index.tsx
Fix USDC logo to show up when wallet is disconnected
https://linear.app/dopex/issue/DOP-443
| desktop |   
|     
|
go to /atlantics/manage/WETH-PUTS-WEEKLY and disconnect wallet to see the USDC logo
> fix: usdc logo error

- apps/dapp/src/components/common/ConnectButton/index.tsx
- apps/dapp/src/components/scalps/DepositCard/index.tsx
Show connect button if wallet isn't connected
[closes issue-###](https://linear.app/dopex/issue/DOP-442/scalps-the-approve-button-is-clickable-and-goes-to-loading-state-even)
With @pair
| desktop |   
|   
|
Disconnect wallet and go to scalps page.
> fix: show connect button when wallet isnt connected

- apps/dapp/src/components/portfolio/Deposits/index.tsx
Show asset for straddle.
closes https://linear.app/dopex/issue/DOP-455/portfolio-in-deposit-straddle-section-there-is-no-way-to-tell-which
With @pair
| desktop |        |  
|
Navigate to /portfolio and see straddle has asset name.
> fix: show straddle asset

- apps/dapp/src/components/UI/Input/index.tsx
- apps/dapp/src/components/ssov/DepositPanel/index.tsx
- apps/dapp/src/components/ssov/PurchaseDialog/index.tsx
- apps/dapp/src/components/straddles/PurchaseCard/index.tsx
- apps/dapp/src/utils/1inch/get1inchQuote.ts
- apps/dapp/src/utils/1inch/get1inchSwap.ts
Fixes 1inch API calls since they added auth requirements
Use the Dopex API to delegate 1inch api calls using auth requirements
N/A
MATIC Straddle purchasing should work as normal
> fix: 1inch api calls

- apps/dapp/src/components/ssov-beta/AsidePanel/index.tsx
- apps/dapp/src/components/ssov-beta/Tables/StrikesChain/StrikeTable.tsx
Fix incorrect breakeven values across the SSOV Beta page.
With @pair
Breakeven calculation for calls didn't account for underlying price.
| desktop |  ![image](https://github.com/dopex-io/elvarg/assets/85767768/ffc2a32c-5b27-431f-bf1d-e741bf001090)   | <img width="1343" alt="Screenshot 2023-08-14" src="https://github.com/dopex-io/elvarg/assets/85767768/a96ea9c5-bf5f-4b37-81cd-f0273b9921e7">   |
Test breakeven prices for both puts and calls, across different markets. Use the following formula:
```
PUT: breakeven = strike - premiumInUSD
CALL: breakeven = strike + premiumInUSD
```
> fix(ssov-beta): breakeven calculation

- apps/dapp/src/components/ssov-beta/AsidePanel/index.tsx
- apps/dapp/src/constants/ssov/markets.ts
- packages/ui/src/Input.tsx
The expiry pills in stETH ssovs are inconsistent with other markets. The intended order is weeklies to the left and monthlies to the right.
Some additional changes made in this PR:
- Increase width of Input component in dopex-io/ui
- Allow users to view their balance and click on their balance to input their entire balance
- Page-crashing bug caused by decimal value in input panel when user toggles between ssov side or expiry.
cc. [DOP-462](https://linear.app/dopex/issue/DOP-462/show-token-balance-on-the-ui), [DOP-464](https://linear.app/dopex/issue/DOP-464/input-box-only-display-the-first-6-digits)
Changed the constants/ssov/markets.ts config for stETH
| desktop |   <img width="285" alt="Screenshot 2023-08-14" …
> fix(ssov-new): expiry pill ordering & input width (DOP-462)

- apps/dapp/src/components/ssov-beta/AsidePanel/index.tsx
in panel textfield
The Insufficient Balance popup makes an incorrect check. It checks for input amount against user's balance. But it should check total cost in underlying against user balance for the same collateral.
| desktop |    <img width="318" alt="Screenshot 2023-08-20 at 4 30 35 PM" src="https://github.com/dopex-io/elvarg/assets/85767768/4cdf6bfa-e7c9-41c0-a9a5-d0e9d964cdc7">    |   <img width="322" alt="Screenshot 2023-08-20 at 4 29 59 PM" src="https://github.com/dopex-io/elvarg/assets/85767768/c0f694c4-37c6-4dd6-89ae-f9cfa4d27768">    |
Check if the 'Insufficient Balance' popup changes to 'Insufficient Allowance' (if you provided insufficient allowance), another popup, or no popup altogether …
> fix(ssov-beta): insufficient balance bug

- apps/dapp/src/components/ssov-beta/Tables/StrikesChain/StrikeTable.tsx
Align the disclosure items with parent row in the SSOV's option chain.
Reduce number of columns from 5 to 4, and add appropriate padding based on parent's td element.
| desktop |  <img width="800" alt="Screenshot 2023-08-28" src="https://github.com/dopex-io/elvarg/assets/85767768/0fefbe67-1062-4981-bc7a-57eb19b4752b"> |  <img width="801" alt="Screenshot 2023-08-28" src="https://github.com/dopex-io/elvarg/assets/85767768/97e37568-0fc5-4171-9ffa-a76299a1bb57"> |
Expand the strike details in the option chain. Inspect via cmd/ctrl + shift + C and hover over items to confirm alignment.
> fix(ssov-beta): disclosure content alignment

- apps/dapp/src/components/scalps/TradeCard/index.tsx
[closes issue-481](https://linear.app/dopex/issue/DOP-481/option-scalp-limit-orders)
When a user toggles the limit order checkbox rawLimitPrice is now automatically updated to the nearest tick, this avoid to show an error if the user clicks Open trade without changing the tick
Open demo link
> fix: option scalp limit orders (DOP-481)

- apps/dapp/src/components/clamm/AsidePanel/components/SelectedStrikeItem/index.tsx
When buying options, input place holder will now show call token symbol for puts and calls instead of the call or put token symbol.
Before: 
After:
> fix: show call symbol for trade

- apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/components/PositionSummary/index.tsx
- apps/dapp/src/components/clamm/PositionsTable/components/Positions/LPPositions/components/PositionSummary/index.tsx
- apps/dapp/src/utils/general/formatAmount.ts
scope:
Increase decimals of details in positions summary and let formatAmount util fn return 0 if the value input to it is 0
before:
after:
> fix: positions summary decimals

- apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/components/PositionSummary/index.tsx
- apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx
Fix spilling position summary inside the Buy Positions table. See the Images attached below.
A core component of the clamm UI is not responsive in smaller viewports and spills over the table as seen in the image below. This PR aims to resolve this issue.
[closes issue-640](https://linear.app/stryke/issue/ENG-640/fix-position-summary-ui-in-smaller-viewports-in-clamm-ui)
Add appropriate tailwind classes for different css breakpoints
| desktop |  <img width="1233" alt="Screenshot 2024-03-14" src="https://github.com/dopex-io/elvarg/assets/85767768/276f62a7-059f-43a3-b2ac-b96014a24ae4">  |  <img width="1208" alt="Screenshot 2024-03-14" src="https://github.com/dopex-io/elvarg/assets/85767768/89aabf9e-9fc3-4b1c-894d-55b932d5a2b0"> |
| …
> fix(clamm): spilling position summary in smaller viewports (eng-640)
